### ISSUE TITLE
Bomb Defusal Patches & Discussion

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/volunteer#28] opened 2016-08-31 14:53 UTC
The repository 'thebomb' has been migrated into this volunteer repository to consolidate general ETC  development discussion into a single repository. This will make it easier to check in on discussions  without having to check multiple issues sections. As discussion spread out recently it got more sparse, I'm hoping consolidating the topics to a single area will keep the conversations active as possible.

##### Submit a patch
Submission of patches should be put in this [folder](https://github.com/ethereumproject/volunteer/tree/master/Difficulty-Bomb-Defusal/Patch-Proposals)

If you are ready to submit a git diff of a working patch or have a working patch detailed in a technical write-up add the document to this folder.

Once discussion of how the patch works, and if it introduces any other affects concludes info from the discussion and the patch details can be combined to create an [EIP](https://github.com/ethereumproject/eips).

##### Submit an [EIP](https://github.com/ethereumproject/eips)

The [EIP](https://github.com/ethereumproject/eips) repository has been massively updated, it is now ready for people to submit new [EIP](https://github.com/ethereumproject/eips)s. 

After a patch has been discussed it can be formatted into an [EIP](https://github.com/ethereumproject/eips) using the template in the repository and submitted.

The [EIP](https://github.com/ethereumproject/eips) will be announced to the wider community, and if they accept the changes it will be immediately implemented in all Ethereum classic clients maintained by the Ethereum Project.

**Comment by elaineo** [comment] 2016-09-02 17:21
@whatisgravity Don't we need to come to an agreement (at least among clients)  over the difficulty adjustment post-patch, or are we just returning the minimum difficulty before exponential factor?

Also, I assume the patches are only modifying the difficulty and block validation, and will not make any modifications as far as fork deployment/management.

**Comment by arvicco** [comment] 2016-09-02 20:09
I think bomb defusion hard fork should be tied to other critical changes:
1) Addressing uncontrolled DAG growth
2) Addressing monetary schedule
3) Reply attacks

All 4 issues require a hard fork for resolution, so ideally all 4 should be addressed by a single hard fork to avoid disruptions caused by separate HF events. @snaproll (on Slack) was working on a document to summarize the issues and our options. It would be good to involve him into this discussion but I don't know his Github nick.

**Comment by realcodywburns** [comment] 2016-09-03 20:38
I do not believe there is an issue with the monetary schedule.  5 etc a block is very conservative.  With that pace, etc might hit 1 billion coins around 2100. It is not as pressing as the difficulty problem. @Elaine we should just be able define a block and snip off the exponential factor. The rest of the equation would regulate the difficulty back to the level needed for normal operation. But it would need to happen across all clients in eodem tempore. The most fair method, imho, would be a fork flag on the clients a la --oppose-dao-fork. This is also the time to purge the metropolis code. Replacing it with the new phase of classic

**Comment by arvicco** [comment] 2016-09-28 15:35
Discussion moved to: https://github.com/ethereumproject/ECIPs/issues/4

**Closed by arvicco** 2016-09-28 15:35 UTC
